registries: # add as many platforms as wished
 - platform: # name of the platform, to be saved in the results
   registry-url: # url for registry API requests
   username: # registry username
   password:  # registry password
   repository:  # registry repository, syntax depends on the registry used, usually username/repository
   upload-manifest: # generate and push manifest together with layers
   region: # region for the experiment, use only with private registries
   account-id: # used for AWS ECR testing, can be removed otherwise

pull-source-folder: 10-10-57a426 # folder for generated layes and images that are stored for push and pull experiments

image-generation: # config for generating synthetic image, size of the layer is full size of the image divided by the layer number
  img-size-mb: 1 # full size of the image
  layer-number: 1 # number of layers
  generate-random: true # generate all zero's (false) or random bytes (true)

gcloud-key: # used for google cloud authentication (JSON key authentication)

trace-replayer: 
  trace-path:  # path for the traces
  clients-number: 3 # number of TR clients
  client-threads: 100 # number of threads per client
  trace-directory:  # trace-directory for DAS ex: /home/user/trace
  trace-files: # name of the trace file, without the full path, full path should be trace-path/trace-files-name
    
  wait: true # delay (true) and stress (false)
  warmup-threads: 10 # number of threads that the master is used for prewarming
  master-port: 8086 # port for the master
  results-directory:  # path for the results directory
  